dependencies:
- base >= 4.7 && < 5
- ghc-lib-parser

executables:
  paxos:
    main:                Main.hs
    source-dirs:         src
    default-extensions:
    - LambdaCase
    - TupleSections
    - RankNTypes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
