dependencies:
- base >= 4.7 && < 5
- haskell-src-exts
- containers
- optparse-applicative
- directory
- filepath
- isocline

executables:
  hs-search:
    main:                Main.hs
    source-dirs:         src
    default-extensions:
    - LambdaCase
    - TupleSections
    - RankNTypes
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
